language: go

go:
  - 1.7.x

before_install: make fmt 2>&1 | read; [ $? == 1 ]

install: make build

script: make test

notifications:
  email:
    recipients:
      - matt@mattbutterfield.com
    on_success: change
    on_failure: always
